### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Daijinryuu** [LilZevi/Amino-Tools#2]
~/Amino-Tools $ python Amino-Tools.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Amino-Tools/Amino-Tools.py", line 3, in <module>
    from amino_tools_configs import main_functions
  File "/data/data/com.termux/files/home/Amino-Tools/amino_tools_configs/main_functions.py", line 2, in <module>
    import aminofix.asyncfix
ModuleNotFoundError: No module named 'aminofix.asyncfix'
~/Amino-Tools $

**Comment by Minori100** [comment]
pip install amino.fix==2.0.4.5

there is no async version in the lastest version

**Comment by Daijinryuu** [comment]
File "/data/data/com.termux/files/home/Amino-Tools/Amino-Tools.py", line 9, in <module>
    asyncio.get_event_loop().run_until_complete(main_functions.main())
  File "/data/data/com.termux/files/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/home/Amino-Tools/amino_tools_configs/main_functions.py", line 384, in main
    await ip_recipient()
  File "/data/data/com.termux/files/home/Amino-Tools/amino_tools_configs/main_functions.py", line 277, in ip_recipient
    if wallet_history.changedCoins[i] > 0:
IndexError: list index out of range
